---
- name: Install Java 17 on Ubuntu
  hosts: aws
  become: yes

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        var: java_version_output.stdout
